### ISSUE TITLE
Container fails to install Python dependencies since #14

### ISSUE THREAD

**Issue by timothymeyers** [marlinspike/dsopbuilder#16]
Since #14 

While running `pip install '.[dependencies]'` works when testing outside of the container, it fails to execute properly during Docker container build time.

I believe this is due to the container building and running as root. The new PEP guidelines appear to have guardrails against pip installs as root, and the pyproject.toml file is unable to be properly read.

**Proposal 1**: Generate requirements.txt at container build time using `pipreqs`

Replace `RUN pip install '.[dependences]'` with

```
RUN pip install pipreqs \
    && pipreqs . \
    && pip install -r requirements.txt
```

**Proposal 2**: Revert to using the requirements.txt file we had before

**Proposal 3**: Possibly for the future, update the container to not build or run as root. I tried to do this but it proved to be too much of a headache to unwind at this time.

**Comment by marlinspike** [comment]
Fixed using recommendation in Proposal 1.
